// <auto-generated />
using System;
using InvoiceFlow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvoiceFlow.Infrastructure.Data.Migrations
{
    [DbContext(typeof(InvoiceFlowDbContext))]
    partial class InvoiceFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvoiceFlow.Core.Entities.ApprovalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_approval_requests_tenant_status");

                    b.ToTable("approval_requests", (string)null);
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Details")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreviousHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_audit_logs_created_at");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("TenantId", "Action")
                        .HasDatabaseName("IX_audit_logs_tenant_action");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.ComplianceConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Model")
                        .HasColumnType("integer");

                    b.Property<bool>("SandboxMode")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CountryCode", "Model")
                        .IsUnique()
                        .HasDatabaseName("IX_compliance_configs_tenant_country_model");

                    b.ToTable("compliance_configs", (string)null);
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.ConnectorConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConnectorType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialsJson")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("ExtraConfigJson")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<int?>("FailedSyncs")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SandboxMode")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SyncDirection")
                        .HasColumnType("integer");

                    b.Property<int?>("SyncIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TotalSynced")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ConnectorType")
                        .HasDatabaseName("IX_connector_configs_tenant_type");

                    b.ToTable("connector_configs", (string)null);
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Checksum")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Folder")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsLatestVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("LinkedCreditNoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LinkedDebitNoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LinkedDeliveryNoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LinkedInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LinkedPurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LinkedReminderId")
                        .HasColumnType("uuid");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OcrText")
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)");

                    b.Property<Guid?>("OriginalDocumentId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Tags")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("LinkedCreditNoteId")
                        .HasDatabaseName("IX_documents_linked_credit_note");

                    b.HasIndex("LinkedDebitNoteId")
                        .HasDatabaseName("IX_documents_linked_debit_note");

                    b.HasIndex("LinkedDeliveryNoteId")
                        .HasDatabaseName("IX_documents_linked_delivery_note");

                    b.HasIndex("LinkedInvoiceId")
                        .HasDatabaseName("IX_documents_linked_invoice");

                    b.HasIndex("LinkedPurchaseOrderId")
                        .HasDatabaseName("IX_documents_linked_purchase_order");

                    b.HasIndex("LinkedReminderId")
                        .HasDatabaseName("IX_documents_linked_reminder");

                    b.HasIndex("OriginalDocumentId")
                        .HasDatabaseName("IX_documents_original_document");

                    b.HasIndex("TenantId", "Checksum")
                        .HasDatabaseName("IX_documents_tenant_checksum")
                        .HasFilter("checksum IS NOT NULL");

                    b.HasIndex("TenantId", "DocumentType")
                        .HasDatabaseName("IX_documents_tenant_type");

                    b.HasIndex("TenantId", "IsLatestVersion")
                        .HasDatabaseName("IX_documents_tenant_latest");

                    b.HasIndex("TenantId", "OriginalDocumentId", "Version")
                        .HasDatabaseName("IX_documents_tenant_original_version");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComplianceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ComplianceModel")
                        .HasColumnType("integer");

                    b.Property<string>("ComplianceResponse")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompliantAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErpId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExtractionMethod")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("IssuerAddress")
                        .HasColumnType("text");

                    b.Property<string>("IssuerEmail")
                        .HasColumnType("text");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("IssuerTaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<double?>("OcrConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RecipientAddress")
                        .HasColumnType("text");

                    b.Property<string>("RecipientEmail")
                        .HasColumnType("text");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("RecipientTaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<decimal?>("ShippingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TransmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.DocumentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("numeric");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("HsnCode")
                        .HasColumnType("text");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductCode")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("TaxCategory")
                        .HasColumnType("text");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentLines");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.DocumentRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceDocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetDocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetTenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_document_relationships_created_at");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_document_relationships_created_by_user");

                    b.HasIndex("RelationshipType")
                        .HasDatabaseName("IX_document_relationships_type");

                    b.HasIndex("TargetDocumentId");

                    b.HasIndex("TargetTenantId");

                    b.HasIndex("TenantId", "SourceDocumentId")
                        .HasDatabaseName("IX_document_relationships_tenant_source");

                    b.HasIndex("TenantId", "TargetDocumentId")
                        .HasDatabaseName("IX_document_relationships_tenant_target");

                    b.HasIndex("SourceDocumentId", "TargetDocumentId", "RelationshipType")
                        .IsUnique()
                        .HasDatabaseName("IX_document_relationships_source_target_type");

                    b.ToTable("document_relationships", (string)null);
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.DocumentVersionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeDetails")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<int>("ChangeType")
                        .HasColumnType("integer");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FieldName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChangeType")
                        .HasDatabaseName("IX_document_version_histories_change_type");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_document_version_histories_created_at");

                    b.HasIndex("DocumentId", "FieldName")
                        .HasDatabaseName("IX_document_version_histories_document_field");

                    b.HasIndex("DocumentId", "Version")
                        .IsUnique()
                        .HasDatabaseName("IX_document_version_histories_document_version");

                    b.HasIndex("TenantId", "DocumentId")
                        .HasDatabaseName("IX_document_version_histories_tenant_document");

                    b.ToTable("document_version_histories", (string)null);
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("BuyerTaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ComplianceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ComplianceModel")
                        .HasColumnType("integer");

                    b.Property<string>("ComplianceResponse")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompliantAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErpId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExtractionMethod")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<double?>("OcrConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("ShippingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TransmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VendorEmail")
                        .HasColumnType("text");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("VendorTaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "InvoiceDate")
                        .HasDatabaseName("IX_invoices_tenant_date");

                    b.HasIndex("TenantId", "InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_invoices_tenant_number");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_invoices_tenant_status");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HsnCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TaxCategory")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_invoice_lines_invoice_linenum");

                    b.ToTable("invoice_lines", (string)null);
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("IX_users_tenant_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.WebhookConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Events")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("SuccessCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_webhook_configs_tenant_name");

                    b.ToTable("webhook_configs", (string)null);
                });

            modelBuilder.Entity("InvoiceFlow.Infrastructure.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_refresh_tokens_user_id");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("IX_refresh_tokens_user_revoked");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.CreditNote", b =>
                {
                    b.HasBaseType("InvoiceFlow.Core.Entities.DocumentEntity");

                    b.Property<Guid?>("OriginalInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasIndex("DeletedByUserId")
                        .HasDatabaseName("IX_credit_notes_deleted_by_user");

                    b.HasIndex("OriginalInvoiceId")
                        .HasDatabaseName("IX_credit_notes_original_invoice");

                    b.HasIndex("TenantId", "DocumentDate")
                        .HasDatabaseName("IX_credit_notes_tenant_date");

                    b.HasIndex("TenantId", "DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_credit_notes_tenant_number");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_credit_notes_tenant_deleted");

                    b.ToTable("credit_notes", (string)null);
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.DebitNote", b =>
                {
                    b.HasBaseType("InvoiceFlow.Core.Entities.DocumentEntity");

                    b.Property<Guid?>("OriginalInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasIndex("DeletedByUserId")
                        .HasDatabaseName("IX_debit_notes_deleted_by_user");

                    b.HasIndex("OriginalInvoiceId")
                        .HasDatabaseName("IX_debit_notes_original_invoice");

                    b.HasIndex("TenantId", "DocumentDate")
                        .HasDatabaseName("IX_debit_notes_tenant_date");

                    b.HasIndex("TenantId", "DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_debit_notes_tenant_number");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_debit_notes_tenant_deleted");

                    b.ToTable("debit_notes", (string)null);
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.DeliveryNote", b =>
                {
                    b.HasBaseType("InvoiceFlow.Core.Entities.DocumentEntity");

                    b.Property<string>("CarrierName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DeliveredQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ProofOfDeliveryPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReceivedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ReceiverSignature")
                        .HasColumnType("text");

                    b.Property<string>("SignaturePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasIndex("DeletedByUserId")
                        .HasDatabaseName("IX_delivery_notes_deleted_by_user");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("IX_delivery_notes_purchase_order");

                    b.HasIndex("TrackingNumber")
                        .HasDatabaseName("IX_delivery_notes_tracking");

                    b.HasIndex("TenantId", "DocumentDate")
                        .HasDatabaseName("IX_delivery_notes_tenant_date");

                    b.HasIndex("TenantId", "DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_delivery_notes_tenant_number");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_delivery_notes_tenant_deleted");

                    b.ToTable("delivery_notes", (string)null);
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.PurchaseOrder", b =>
                {
                    b.HasBaseType("InvoiceFlow.Core.Entities.DocumentEntity");

                    b.Property<string>("BillToAddress")
                        .HasColumnType("text");

                    b.Property<string>("BillToName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Incoterms")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShipToAddress")
                        .HasColumnType("text");

                    b.Property<string>("ShipToName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasIndex("DeletedByUserId")
                        .HasDatabaseName("IX_purchase_orders_deleted_by_user");

                    b.HasIndex("ExpectedDeliveryDate")
                        .HasDatabaseName("IX_purchase_orders_expected_delivery");

                    b.HasIndex("TenantId", "DocumentDate")
                        .HasDatabaseName("IX_purchase_orders_tenant_date");

                    b.HasIndex("TenantId", "DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_purchase_orders_tenant_number");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_purchase_orders_tenant_deleted");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_purchase_orders_tenant_status");

                    b.ToTable("purchase_orders", (string)null);
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.Reminder", b =>
                {
                    b.HasBaseType("InvoiceFlow.Core.Entities.DocumentEntity");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DaysOverdue")
                        .HasColumnType("integer");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ReminderFee")
                        .HasColumnType("numeric");

                    b.Property<int>("ReminderLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasIndex("DeletedByUserId")
                        .HasDatabaseName("IX_reminders_deleted_by_user");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IX_reminders_due_date");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("IX_reminders_invoice");

                    b.HasIndex("ReminderLevel")
                        .HasDatabaseName("IX_reminders_level");

                    b.HasIndex("TenantId", "DocumentDate")
                        .HasDatabaseName("IX_reminders_tenant_date");

                    b.HasIndex("TenantId", "DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_reminders_tenant_number");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("IX_reminders_tenant_deleted");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_reminders_tenant_status");

                    b.ToTable("reminders", (string)null);
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.ApprovalRequest", b =>
                {
                    b.HasOne("InvoiceFlow.Core.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InvoiceFlow.Core.Entities.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceFlow.Core.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InvoiceFlow.Core.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("Invoice");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("InvoiceFlow.Core.Entities.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.ComplianceConfig", b =>
                {
                    b.HasOne("InvoiceFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.ConnectorConfig", b =>
                {
                    b.HasOne("InvoiceFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.Document", b =>
                {
                    b.HasOne("InvoiceFlow.Core.Entities.CreditNote", "LinkedCreditNote")
                        .WithMany()
                        .HasForeignKey("LinkedCreditNoteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InvoiceFlow.Core.Entities.DebitNote", "LinkedDebitNote")
                        .WithMany()
                        .HasForeignKey("LinkedDebitNoteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InvoiceFlow.Core.Entities.DeliveryNote", "LinkedDeliveryNote")
                        .WithMany()
                        .HasForeignKey("LinkedDeliveryNoteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InvoiceFlow.Core.Entities.Invoice", "LinkedInvoice")
                        .WithMany()
                        .HasForeignKey("LinkedInvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InvoiceFlow.Core.Entities.PurchaseOrder", "LinkedPurchaseOrder")
                        .WithMany()
                        .HasForeignKey("LinkedPurchaseOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InvoiceFlow.Core.Entities.Reminder", "LinkedReminder")
                        .WithMany()
                        .HasForeignKey("LinkedReminderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InvoiceFlow.Core.Entities.Document", "OriginalDocument")
                        .WithMany("Versions")
                        .HasForeignKey("OriginalDocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InvoiceFlow.Core.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LinkedCreditNote");

                    b.Navigation("LinkedDebitNote");

                    b.Navigation("LinkedDeliveryNote");

                    b.Navigation("LinkedInvoice");

                    b.Navigation("LinkedPurchaseOrder");

                    b.Navigation("LinkedReminder");

                    b.Navigation("OriginalDocument");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.DocumentEntity", b =>
                {
                    b.HasOne("InvoiceFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.DocumentLine", b =>
                {
                    b.HasOne("InvoiceFlow.Core.Entities.DocumentEntity", "Document")
                        .WithMany("Lines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.DocumentRelationship", b =>
                {
                    b.HasOne("InvoiceFlow.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InvoiceFlow.Core.Entities.Document", "SourceDocument")
                        .WithMany("OutgoingRelationships")
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoiceFlow.Core.Entities.Document", "TargetDocument")
                        .WithMany("IncomingRelationships")
                        .HasForeignKey("TargetDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoiceFlow.Core.Entities.Tenant", "TargetTenant")
                        .WithMany()
                        .HasForeignKey("TargetTenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InvoiceFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("SourceDocument");

                    b.Navigation("TargetDocument");

                    b.Navigation("TargetTenant");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.DocumentVersionHistory", b =>
                {
                    b.HasOne("InvoiceFlow.Core.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InvoiceFlow.Core.Entities.Document", "Document")
                        .WithMany("VersionHistory")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Document");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.Invoice", b =>
                {
                    b.HasOne("InvoiceFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.InvoiceLine", b =>
                {
                    b.HasOne("InvoiceFlow.Core.Entities.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.User", b =>
                {
                    b.HasOne("InvoiceFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.WebhookConfig", b =>
                {
                    b.HasOne("InvoiceFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("InvoiceFlow.Infrastructure.Auth.RefreshToken", b =>
                {
                    b.HasOne("InvoiceFlow.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.CreditNote", b =>
                {
                    b.HasOne("InvoiceFlow.Core.Entities.Invoice", "OriginalInvoice")
                        .WithMany()
                        .HasForeignKey("OriginalInvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OriginalInvoice");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.DebitNote", b =>
                {
                    b.HasOne("InvoiceFlow.Core.Entities.Invoice", "OriginalInvoice")
                        .WithMany()
                        .HasForeignKey("OriginalInvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OriginalInvoice");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.DeliveryNote", b =>
                {
                    b.HasOne("InvoiceFlow.Core.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.Reminder", b =>
                {
                    b.HasOne("InvoiceFlow.Core.Entities.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.Document", b =>
                {
                    b.Navigation("IncomingRelationships");

                    b.Navigation("OutgoingRelationships");

                    b.Navigation("VersionHistory");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.DocumentEntity", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("InvoiceFlow.Core.Entities.Invoice", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
