/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and receive JWT token */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user and tenant */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user info */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List invoices with pagination and filters */
        get: operations["listInvoices"];
        put?: never;
        /** Create a new invoice (manual entry) */
        post: operations["createInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get invoice by ID */
        get: operations["getInvoice"];
        /** Update invoice */
        put: operations["updateInvoice"];
        post?: never;
        /** Delete invoice */
        delete: operations["deleteInvoice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{invoice_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve invoice for compliance processing */
        post: operations["approveInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{invoice_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject invoice */
        post: operations["rejectInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an invoice file for processing */
        post: operations["uploadInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive invoice via webhook */
        post: operations["webhookReceive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion/poll/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger email inbox poll */
        post: operations["triggerEmailPoll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion/poll/ftp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger FTP folder poll */
        post: operations["triggerFtpPoll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion/poll/sftp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger SFTP folder poll */
        post: operations["triggerSftpPoll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ingestion statistics */
        get: operations["getIngestionStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion/task/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check ingestion task status */
        get: operations["getIngestionTaskStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard statistics */
        get: operations["getDashboardStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/charts/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get daily invoice volume for charts */
        get: operations["getDailyVolume"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/charts/by-country": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get invoice counts by country */
        get: operations["getByCountry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get compliance status summary */
        get: operations["getComplianceStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/validate/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate invoice against compliance rules (pre-check) */
        post: operations["validateCompliance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/process/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger compliance processing */
        post: operations["processCompliance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/process-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger batch compliance processing */
        post: operations["processBatchCompliance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/transmit/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transmit compliant invoice to network */
        post: operations["transmitInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/archive/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive invoice for post-audit compliance */
        post: operations["archiveInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List compliance configurations */
        get: operations["listComplianceConfigs"];
        put?: never;
        /** Create compliance configuration */
        post: operations["createComplianceConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/task/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check compliance task status */
        get: operations["checkComplianceTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extraction/extract/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger AI extraction for an invoice */
        post: operations["triggerExtraction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extraction/extract-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger batch extraction */
        post: operations["triggerBatchExtraction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extraction/status/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get extraction status for an invoice */
        get: operations["getExtractionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tenant settings */
        get: operations["getSettings"];
        /** Update tenant settings */
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available country compliance configurations */
        get: operations["listCountryConfigs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available ERP connector types */
        get: operations["listAvailableConnectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured connectors */
        get: operations["listConfiguredConnectors"];
        put?: never;
        /** Create ERP connector configuration */
        post: operations["createConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{connector_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get connector configuration */
        get: operations["getConnector"];
        put?: never;
        post?: never;
        /** Delete connector configuration */
        delete: operations["deleteConnector"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{connector_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test ERP connection */
        post: operations["testConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{connector_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync invoices with ERP */
        post: operations["syncConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{connector_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate connector */
        post: operations["activateConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{connector_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate connector */
        post: operations["deactivateConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List supported webhook event types */
        get: operations["listWebhookEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List webhook configurations */
        get: operations["listWebhooks"];
        put?: never;
        /** Create webhook configuration */
        post: operations["createWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/{webhook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get webhook configuration */
        get: operations["getWebhook"];
        /** Update webhook configuration */
        put: operations["updateWebhook"];
        post?: never;
        /** Delete webhook */
        delete: operations["deleteWebhook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/{webhook_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send test event to webhook */
        post: operations["testWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/{webhook_id}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle webhook active/inactive */
        post: operations["toggleWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        InvoiceStatus: "received" | "processing" | "extracted" | "reviewing" | "approved" | "compliant" | "transmitted" | "failed" | "rejected";
        /** @enum {string} */
        ComplianceModel: "peppol" | "clearance" | "ctc" | "post_audit";
        /** @enum {string} */
        ExtractionMethod: "ocr" | "llm" | "xml" | "manual";
        /** @enum {string} */
        IngestionSource: "email" | "ftp" | "sftp" | "api" | "webhook" | "manual";
        InvoiceLine: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            invoice_id: string;
            line_number: number;
            description?: string | null;
            quantity: number;
            unit_price: number;
            tax_rate: number;
            tax_amount: number;
            line_total: number;
            item_code?: string | null;
        };
        InvoiceLineCreate: {
            line_number: number;
            description?: string | null;
            /** @default 1 */
            quantity: number;
            /** @default 0 */
            unit_price: number;
            /** @default 0 */
            tax_rate: number;
            item_code?: string | null;
        };
        Invoice: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            status: components["schemas"]["InvoiceStatus"];
            invoice_number: string;
            vendor_name: string;
            vendor_tax_id?: string | null;
            buyer_name?: string | null;
            buyer_tax_id?: string | null;
            /** Format: date-time */
            invoice_date?: string | null;
            /** Format: date-time */
            due_date?: string | null;
            currency: string;
            subtotal: number;
            tax_amount: number;
            total_amount: number;
            country_code: string;
            compliance_model: components["schemas"]["ComplianceModel"];
            source: components["schemas"]["IngestionSource"];
            source_reference?: string | null;
            file_url?: string | null;
            original_filename?: string | null;
            ocr_confidence?: number | null;
            extraction_method?: components["schemas"]["ExtractionMethod"];
            extracted_data?: {
                [key: string]: unknown;
            };
            compliance_response?: {
                [key: string]: unknown;
            };
            error_message?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            lines?: components["schemas"]["InvoiceLine"][];
            /** @description Audit trail entries (included in detail view) */
            audit_log?: components["schemas"]["AuditLog"][];
        };
        InvoiceCreate: {
            invoice_number: string;
            vendor_name: string;
            vendor_tax_id?: string | null;
            buyer_name?: string | null;
            buyer_tax_id?: string | null;
            /** Format: date-time */
            invoice_date?: string | null;
            /** Format: date-time */
            due_date?: string | null;
            /** @default USD */
            currency: string;
            country_code: string;
            compliance_model: components["schemas"]["ComplianceModel"];
            /** @default [] */
            lines: components["schemas"]["InvoiceLineCreate"][];
        };
        InvoiceUpdate: {
            invoice_number?: string | null;
            vendor_name?: string | null;
            vendor_tax_id?: string | null;
            buyer_name?: string | null;
            buyer_tax_id?: string | null;
            /** Format: date-time */
            invoice_date?: string | null;
            /** Format: date-time */
            due_date?: string | null;
            currency?: string | null;
            status?: components["schemas"]["InvoiceStatus"];
        };
        InvoiceListResponse: {
            invoices: components["schemas"]["Invoice"][];
            total: number;
            page: number;
            page_size: number;
        };
        AuditLog: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            invoice_id?: string | null;
            action: string;
            details?: {
                [key: string]: unknown;
            };
            user_id?: string | null;
            /** Format: date-time */
            timestamp: string;
        };
        TokenRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        TokenResponse: {
            access_token: string;
            /** @default bearer */
            token_type: string;
            user_id: string;
            tenant_id: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            full_name?: string | null;
            tenant_name: string;
            tenant_slug: string;
            /** @default US */
            country_code: string;
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            full_name?: string | null;
            role: string;
            /** Format: uuid */
            tenant_id: string;
        };
        FileUploadResponse: {
            /**
             * Format: uuid
             * @description Null when processing is async; use task_id for tracking
             */
            invoice_id?: string | null;
            status: components["schemas"]["InvoiceStatus"];
            filename: string;
            message: string;
        };
        PollResponse: {
            task_id: string;
            source_type: components["schemas"]["IngestionSource"];
            status: string;
            message: string;
        };
        IngestionStatsResponse: {
            total_ingested: number;
            by_source: {
                [key: string]: number;
            };
            /** Format: date-time */
            last_poll_at?: string | null;
            pending_processing: number;
        };
        WebhookPayload: {
            filename: string;
            /** @description Base64-encoded file content */
            file_content_b64: string;
            /** @default application/pdf */
            mime_type: string;
            source_reference?: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        TaskStatusResponse: {
            task_id: string;
            status: string;
            result?: string | null;
            traceback?: string | null;
        };
        DashboardStats: {
            invoices_today: number;
            success_rate: number;
            pending: number;
            total_processed: number;
        };
        ChartData: {
            labels: string[];
            data: number[];
        };
        ComplianceStatusResponse: {
            pending: number;
            compliant: number;
            failed: number;
        };
        ComplianceValidationResponse: {
            valid: boolean;
            errors: string[];
            warnings: string[];
        };
        ComplianceConfigCreate: {
            country_code: string;
            /** @enum {string} */
            model: "peppol" | "clearance" | "ctc" | "post_audit";
            /** @default true */
            enabled: boolean;
            config?: {
                [key: string]: unknown;
            };
        };
        ComplianceConfigResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            country_code: string;
            model: string;
            enabled: boolean;
            config: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ExtractionStatusResponse: {
            invoice_id: string;
            status: components["schemas"]["InvoiceStatus"];
            extraction_method?: components["schemas"]["ExtractionMethod"];
            ocr_confidence?: number | null;
            error_message?: string | null;
            /** Format: date-time */
            processing_started_at?: string | null;
            /** Format: date-time */
            processing_completed_at?: string | null;
        };
        TenantSettings: {
            settings: {
                tenant_name?: string;
                country_code?: string;
                default_currency?: string;
                default_compliance_model?: string;
                tax_id?: string | null;
                registration_number?: string | null;
                custom_settings?: {
                    [key: string]: unknown;
                };
            };
        };
        CountryConfig: {
            code: string;
            name: string;
            model: string;
            system: string;
        };
        CountryConfigList: {
            countries: components["schemas"]["CountryConfig"][];
        };
        AvailableConnector: {
            type: string;
            display_name: string;
            directions: string[];
        };
        ConnectorCreate: {
            /** @enum {string} */
            connector_type: "sap" | "oracle" | "xero";
            display_name: string;
            api_key?: string | null;
            api_secret?: string | null;
            base_url?: string | null;
            /** @default true */
            sandbox: boolean;
            /** @enum {string} */
            sync_direction?: "push" | "pull" | "bidirectional";
            extra_config?: {
                [key: string]: unknown;
            };
        };
        ConnectorResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            connector_type: string;
            display_name: string;
            /** @enum {string} */
            status: "active" | "inactive" | "error" | "pending_auth";
            sandbox: boolean;
            sync_direction: string;
            /** Format: date-time */
            last_sync_at?: string | null;
            total_synced?: number;
            total_failed?: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ConnectorSyncRequest: {
            /** @enum {string} */
            direction: "push" | "pull";
            /** Format: uuid */
            invoice_id?: string | null;
            invoice_ids?: string[] | null;
            /** Format: date-time */
            since?: string | null;
            /** @default 100 */
            limit: number;
        };
        ConnectorSyncResponse: {
            success: boolean;
            connector_type: string;
            direction: string;
            records_synced: number;
            records_failed: number;
            erp_ids: string[];
            errors: string[];
            warnings: string[];
            raw_response?: {
                [key: string]: unknown;
            } | null;
        };
        ConnectorTestResponse: {
            connector: string;
            status: string;
            sandbox?: boolean;
            message: string;
            auth_url?: string | null;
        };
        WebhookCreate: {
            name: string;
            /** Format: uri */
            url: string;
            secret?: string | null;
            events: string[];
            /** @default application/json */
            content_type: string;
            /** @default 30 */
            timeout_seconds: number;
            /** @default 3 */
            max_retries: number;
            /** @default true */
            active: boolean;
        };
        WebhookUpdate: {
            name?: string | null;
            /** Format: uri */
            url?: string | null;
            secret?: string | null;
            events?: string[] | null;
            content_type?: string | null;
            timeout_seconds?: number | null;
            max_retries?: number | null;
            active?: boolean | null;
        };
        WebhookResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            name: string;
            url: string;
            active: boolean;
            events: string[];
            content_type: string;
            timeout_seconds: number;
            max_retries: number;
            /** Format: date-time */
            last_triggered_at?: string | null;
            last_status_code?: number | null;
            success_count: number;
            failure_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        WebhookTestResponse: {
            success: boolean;
            status_code?: number | null;
            message: string;
            response_time_ms: number;
        };
        WebhookEventList: string[];
        MessageResponse: {
            message: string;
        };
        ActivationResponse: {
            /** @enum {string} */
            status: "active" | "inactive";
        };
        ToggleResponse: {
            active: boolean;
        };
        ComplianceTaskResponse: {
            task_id: string;
            status: string;
            invoice_id: string;
        };
        BatchComplianceResponse: {
            task_id: string;
            status: string;
            invoice_count: number;
        };
        HealthResponse: {
            status: string;
            service: string;
        };
        ErrorResponse: {
            detail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registration successful */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listInvoices: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                status?: components["schemas"]["InvoiceStatus"];
                country?: string;
                /** @description Search by invoice number or vendor name */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated invoice list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceListResponse"];
                };
            };
        };
    };
    createInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceCreate"];
            };
        };
        responses: {
            /** @description Invoice created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
        };
    };
    getInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
            /** @description Invoice not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceUpdate"];
            };
        };
        responses: {
            /** @description Invoice updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
        };
    };
    deleteInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approveInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
        };
    };
    rejectInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
        };
    };
    uploadInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Invoice file (PDF, XML, PNG, JPEG, TIFF)
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description File uploaded and queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileUploadResponse"];
                };
            };
        };
    };
    webhookReceive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookPayload"];
            };
        };
        responses: {
            /** @description Webhook received */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileUploadResponse"];
                };
            };
        };
    };
    triggerEmailPoll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Poll initiated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollResponse"];
                };
            };
        };
    };
    triggerFtpPoll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Poll initiated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollResponse"];
                };
            };
        };
    };
    triggerSftpPoll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Poll initiated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollResponse"];
                };
            };
        };
    };
    getIngestionStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingestion statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionStatsResponse"];
                };
            };
        };
    };
    getIngestionTaskStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusResponse"];
                };
            };
        };
    };
    getDashboardStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
        };
    };
    getDailyVolume: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily volume data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartData"];
                };
            };
        };
    };
    getByCountry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Country distribution data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartData"];
                };
            };
        };
    };
    getComplianceStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Compliance status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceStatusResponse"];
                };
            };
        };
    };
    validateCompliance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceValidationResponse"];
                };
            };
        };
    };
    processCompliance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Compliance queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceTaskResponse"];
                };
            };
        };
    };
    processBatchCompliance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    invoice_ids: string[];
                };
            };
        };
        responses: {
            /** @description Batch compliance queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchComplianceResponse"];
                };
            };
        };
    };
    transmitInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transmission queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceTaskResponse"];
                };
            };
        };
    };
    archiveInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archive queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceTaskResponse"];
                };
            };
        };
    };
    listComplianceConfigs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Compliance configs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceConfigResponse"][];
                };
            };
        };
    };
    createComplianceConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComplianceConfigCreate"];
            };
        };
        responses: {
            /** @description Config created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceConfigResponse"];
                };
            };
        };
    };
    checkComplianceTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusResponse"];
                };
            };
        };
    };
    triggerExtraction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Extraction queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    triggerBatchExtraction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    invoice_ids: string[];
                };
            };
        };
        responses: {
            /** @description Batch extraction queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    getExtractionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Extraction status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionStatusResponse"];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSettings"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Settings updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        updated: boolean;
                    };
                };
            };
        };
    };
    listCountryConfigs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Country configs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryConfigList"];
                };
            };
        };
    };
    listAvailableConnectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available connectors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableConnector"][];
                };
            };
        };
    };
    listConfiguredConnectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured connectors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorResponse"][];
                };
            };
        };
    };
    createConnector: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectorCreate"];
            };
        };
        responses: {
            /** @description Connector created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorResponse"];
                };
            };
        };
    };
    getConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connector details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorResponse"];
                };
            };
        };
    };
    deleteConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connector deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    testConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection test result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorTestResponse"];
                };
            };
        };
    };
    syncConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectorSyncRequest"];
            };
        };
        responses: {
            /** @description Sync result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorSyncResponse"];
                };
            };
        };
    };
    activateConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connector activated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivationResponse"];
                };
            };
        };
    };
    deactivateConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connector deactivated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivationResponse"];
                };
            };
        };
    };
    listWebhookEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supported events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEventList"];
                };
            };
        };
    };
    listWebhooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook configs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"][];
                };
            };
        };
    };
    createWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookCreate"];
            };
        };
        responses: {
            /** @description Webhook created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
        };
    };
    getWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
        };
    };
    updateWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookUpdate"];
            };
        };
        responses: {
            /** @description Webhook updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
        };
    };
    deleteWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    testWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Test result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookTestResponse"];
                };
            };
        };
    };
    toggleWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Toggle result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToggleResponse"];
                };
            };
        };
    };
}
